W6-SurveyForm
Technigo/project-survey-vite pull request #65
Opened 2024-03-17 18:56 UTC by Maria-Manuela

## Netlify link
https://surveyformbyam.netlify.app/

## Collaborators
[github-vidalhuix]

2024-03-20 13:02 UTC, FridaMari reviewed
Nice app, especially the start, next and back buttons! :) When reading the code it was a bit confusing with the overall structure. Seems like there are some file duplicates.

2024-03-22 07:51 UTC, AntonellaMorittu requested changes
Hi Maria-Manuela, congratulations with your Survey app! ⭐️ You developed a great app with multi-step form and it features all the needed requirements. 
Here's what needs to be improved:
- good practice: the structure can be improved removing the double components inside the `src` folder. Make sure to name the `components` folder just like so
- formatting needs to be applied for both `.jsx`jsx and `.css` files, please check our guide on Notion [here](https://www.notion.so/technigo/How-to-use-VS-Code-5ed620b8e8f24f17bcab6e285958d9b6?pvs=4#a58443dde71c4918a030dc6de3cd62cd) so that from now on all projects will be formatted on save and have the right two-space tab indentation :) Thank you 💪

2024-03-22 07:51 UTC, AntonellaMorittu commented on src/Summary.jsx
pls format this file to remove empty lines on top of the file 🧹

2024-03-22 07:51 UTC, AntonellaMorittu commented on src/Survey.jsx
please format all the files in the app and set the correct n of tabs, you can check your Toolbox on Notion how to set up your Visual Studio Code 👍

2024-03-22 07:51 UTC, AntonellaMorittu commented on src/Footer.jsx
remove the double files, these components (Footer, Header, Summary, Survey) already exist in the components folder, so go ahead and remove them from here 👍

2024-03-22 07:51 UTC, AntonellaMorittu commented on src/assets/Technigo-logo-1.png
remove all unused assets🧹

2024-03-22 07:51 UTC, AntonellaMorittu commented on src/components.survey/Survey.css
format format format 🪄

2024-03-27 07:53 UTC, AntonellaMorittu approved these changes

2024-10-24 09:27 UTC, closed without merging