Project Survey - week 6
Technigo/project-survey-vite pull request #69
Opened 2024-03-17 21:22 UTC by kathinka

## Netlify link

(https://piratenamegenerator.netlify.app/)

## Collaborators
solo

2024-03-20 06:42 UTC, Yifan-858 commented
Hey Kathinka!

What a cute project you made for the week!☺️​Good Job! 

The code is nice and clean that makes it easy to follow.
One thing I've noticed about your file structure is that you have the component files inside the assets folder. That can be a bit confusing. Try to keep all the code files in a dedicated src folder maybe? 🤓​

You managed to get 100% in the Lighthouse accessibility check. That's great!💯
​I find it helps a lot when you include the "Try again" option. Makes the flow much better. I will improve my project with this inspiration ​🤩
There's a minor styling suggestion for the radio box, and I've noted it below where its code is located.

Good job again! 
I really like the theme of your survey. It's fun and spiritual. And it has a smooth flow!  
I can't help myself to run it again and again! 🔮​
I've made a few minor suggestions for you to review whenever you have a moment.

2024-03-22 10:03 UTC, AntonellaMorittu requested changes
Hi Kathrinka, congratulations with your Survey app! ⭐️ You developed a great app with multi-step form and it features all the needed requirements. 
Here's what needs to be improved:
- good practice: the structure can be improved removing the double components inside the `src` and `components` folder (I left comments in the code).
- formatting needs to be applied for both` .jsx `and `.css` files, please check our guide on Notion [here](https://www.notion.so/technigo/How-to-use-VS-Code-5ed620b8e8f24f17bcab6e285958d9b6?pvs=4#a58443dde71c4918a030dc6de3cd62cd) so that from now on all projects will be formatted on save and have the right two-space tab indentation :) 
- layout: items don't seem aligned, take a look at this screenshot:

<img width="468" alt="Screenshot 2024-03-22 at 10 56 00" src="https://github.com/Technigo/project-survey-vite/assets/33493978/d772baa8-a7ab-4df5-b1cc-e9a28e9e3adf">

The menu element is not centered as the submit button for example, looks a bit messy.

Please update the code with the requested changes above.
Thank you 💪

2024-03-27 07:55 UTC, AntonellaMorittu approved these changes

2024-03-27 07:55 UTC, AntonellaMorittu commented on .eslintrc.cjs
Format this file please 🪄

2024-10-24 09:27 UTC, closed without merging