The best you
Technigo/project-survey-vite pull request #71
Opened 2024-03-19 19:57 UTC by johannacatalinismith

## Netlify link

https://thebestyouu.netlify.app/

2024-03-22 10:16 UTC, AntonellaMorittu requested changes
Hello Johanna and congrats with your Survey project! The app satisfies most the requirements. Well done with responsiveness and accessibility, it's needed though that you put in practice the concept of components-props in React as we are teaching in the course, please refactor your code - left a comment - to pass this week's assignment, almost there 💪

2024-03-22 10:16 UTC, AntonellaMorittu commented on src/App.jsx
please keep the `App.jsx` file free from the business logic as much as you can. Refactor creating a separate (or more) component like we thought until now in the BootCamp 👍

2024-03-22 17:43 UTC, johannacatalinismith commented
Hey @AntonellaMorittu! I've done the changes that was required! :)

2024-03-27 07:56 UTC, AntonellaMorittu approved these changes

2024-10-24 09:27 UTC, closed without merging